
//-----------------------------------------------------------------------------
// <auto-generated>
//   This code was generated by a tool.
//
//   Changes to this file may cause incorrect behavior and will be lost if
//   the code is regenerated.
//
//   For more information, see: http://go.microsoft.com/fwlink/?LinkID=623246
// </auto-generated>
//-----------------------------------------------------------------------------
#pragma once

#include <windows.h>
#include <ppltasks.h>
#include <concrt.h>
#include <collection.h>
#include <windows.devices.alljoyn.interop.h>
#include <map>

#include <alljoyn_c/busattachment.h>
#include <alljoyn_c/dbusstddefines.h>
#include <alljoyn_c/AboutData.h>
#include <alljoyn_c/AboutObj.h>
#include <alljoyn_c/AboutObjectDescription.h>

#include "AllJoynHelpers.h"
#include "AllJoynBusObjectManager.h"

#define PROJECT_NAMESPACE com::microsoft::ZWaveBridge::SwitchBinary::Switch

#include "SwitchStructures.h"
#include "TypeConversionHelpers.h"
#include "SwitchMethodResults.h"
#include "SwitchEventArgs.h"
#include "ISwitchService.h"
#include "SwitchSignals.h"
#include "SwitchProducer.h"
#include "SwitchWatcher.h"
#include "SwitchConsumer.h"
#include "SwitchServiceEventArgs.h"
#include "SwitchServiceEventAdapter.h"